baseURL = "http://localhost:1313/"
languageCode = "zh-cn"
title = "北京大学经济学会 EconS"
theme = "ananke"

[pagination]
  pagerSize = 12
[outputs]
  home = ["HTML", "RSS", "JSON"]

[[cascade]]
  layout = "single"
  [cascade._target]
    kind = "page"
    section = ["events", "posts", "people", "moments", "downloads"]
[menu]
  [[menu.main]]
    name = "活动"
    url = "/events/"
    weight = 1
  [[menu.main]]
    name = "贴文"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "成员"
    url = "/people/"
    weight = 3
  [[menu.main]]
    name = "月度回顾"
    url = "/moments/"
    weight = 4
  [[menu.main]]
    name = "资料下载"
    url = "/downloads/"
    weight = 5
[params]
  assets_base = "https://assets.pkuecons.org"
  favicon = "https://assets.pkuecons.org/image/logo.jpg"
  featured_image_mobile = "https://assets.pkuecons.org/image/mobile_hero.jpg"
  cover_dimming_class = "bg-transparent"
  [params.ananke.social.share]
    networks = ["weixin"]
    icons = true
    sharetext = true

  [params.ananke.social.networks.weixin]
    slug = "weixin"
    label = "微信"
    color = "#07C160"
    icon = "weixin"
    link = "https://api.qrserver.com/v1/create-qr-code/"
    [params.ananke.social.networks.weixin.particles]
      data = "permalink"
      params = "size=200x200"
